# Generated by Django 3.2.10 on 2021-12-29 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('comment', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telephone', models.CharField(max_length=50, null=True)),
                ('date_open', models.DateField(default=django.utils.timezone.now)),
                ('date_update', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_close', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('email_status', models.BooleanField(default=True)),
                ('err_email', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contact',
                'ordering': ['id'],
                'permissions': [('admin', 'Puede Administrar los Contact (ver historial, dar de baja)'), ('attend', 'Puede Atender un Contact'), ('register', 'Puede Registrar un nuevo Contact')],
            },
        ),
    ]
