"""
Django settings for gpslink project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import socket
#from config.apps import debug_print 

## FIXME test 'PUESTA_PRODUCTION'
## python manage.py runserver 0.0.0.0:8000 --insecure
# SECURITY WARNING: don't run with debug turned on in production!
PUESTA_PRODUCTION = False
AUTH_USER_MODEL = 'Login.User'
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

def getHostIp() -> str:
  """
    @brief Funcion para obtener la ip del Host, solo valida para
    host del tipo unix|linux
    @return string con la ip del Host, no la ip local '127.0.0.1'
  
  """
  st = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
  try:       
    st.connect(('10.255.255.255', 1))
    IP = st.getsockname()[0]
  except Exception:
    IP = '127.0.0.1'
  finally:
    st.close()
  return f'{IP}'
  


if(PUESTA_PRODUCTION == True):  
  DEBUG = False
  TEMPLATE_DEBUG = False
  ## STEP 02  
  with open(f'{BASE_DIR.parent}/etc/secret_key.txt') as lfile:
    SECRET_KEY = lfile.read().strip()
  ##endwith
  # SECRET_KEY = os.environ['SECRET_KEY']
  ## STEP 03
  ALLOWED_HOSTS = ['127.0.0.1','gpslink.com.cl','www.gpslink.com.cl','0.0.0.0',getHostIp()]

  STATICFILES_DIRS = [
     BASE_DIR/"static"
    ,BASE_DIR/"media/"
    ,'/var/www/static/'
    , ]  
  """
  os.environ['HTTPS'] = "on"
  CSRF_COOKIE_SECURE = False
  SESSION_COOKIE_SECURE = True
  SECURE_SSL_REDIRECT = True
  SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
  SECURE_HSTS_SECONDS = 1
  SECURE_HSTS_INCLUDE_SUBDOMAINS = True
  SECURE_HSTS_PRELOAD = True
  HOST_SCHEME = "https://"
  SECURE_FRAME_DENY = True
  SSL_ERROR_RX_RECORD_TOO_LONG = 10  
  CONN_MAX_AGE = 1    
  """
  ## STATICFILES_FINDERS
  STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder'
    ,'django.contrib.staticfiles.finders.AppDirectoriesFinder'
    ,
  ]
else:
  # Quick-start development settings - unsuitable for production
  # See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/
  # SECURITY WARNING: keep the secret key used in production secret!
  SECRET_KEY = 'django-insecure-z5b_#-m*5mk-eip+td7ub38b4mc=abfjiff%&^376x07d4i9np'
  DEBUG = True
  # ALLOWED_HOSTS = ['0.0.0.0']
  # 
  ## FIXME test responisve local test LAN
  # ALLOWED_HOSTS = ['192.168.0.240','127.0.0.1','0.0.0.0']      
  ALLOWED_HOSTS = ['127.0.0.1','0.0.0.0',getHostIp(),'b6ca68098da033.lhrtunnel.link']
  
  CORS_REPLACE_HTTPS_REFERER      = False
  HOST_SCHEME                     = "http://"
  SECURE_PROXY_SSL_HEADER         = None
  SECURE_SSL_REDIRECT             = False
  SESSION_COOKIE_SECURE           = False
  CSRF_COOKIE_SECURE              = False
  SECURE_HSTS_SECONDS             = None
  SECURE_HSTS_INCLUDE_SUBDOMAINS  = False
  SECURE_FRAME_DENY               = False
##endif


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    ## install
    # 'bootstrap4',
    'multi_email_field',    
    'easy_thumbnails','filer', 'mptt',    
    'xlsxwriter',
    'validate_email',
    ##
    ## TODO Modulos, desarrollados/creados
    ##
    'Home',
    'Login',
    'Contact',
    'Buttons',
    'Table',
    ##
    ## white noise
    ##
]

MIDDLEWARE = [ 
    ##  MIDDLEWARE  'django.contrib.sessions.middleware.SessionMiddleware'
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
      {
          'BACKEND': 'django.template.backends.django.DjangoTemplates',
          'DIRS': ['Login/templates'
                  ,'Contact/templates'
                  ,'Buttons/templates'
                  ,'Table/templates'
                  ,'Desarrollos/templates'
                  ,'Home/templates'
                  ],
          'APP_DIRS': True,
          'OPTIONS': {
              'context_processors': [
                  'django.template.context_processors.debug',
                  'django.template.context_processors.request',
                  'django.contrib.auth.context_processors.auth',
                  'django.contrib.messages.context_processors.messages',
              ],
          },
      },
  ]  
WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

''' 
DATABASES = {
      'default': {
          'ENGINE': 'django.db.backends.postgresql_psycopg2',
          ##-- para test
          'NAME':'db_gpslink_02',
          ##-- para produccion
          #'NAME':'db_gpslink',
          'USER':'postgres',
          'PASSWORD':'123',
          'HOST':'127.0.0.1',
          'DATABASE_PORT' : '5432',            
      }
  }
'''


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#LANGUAGE_CODE = 'es-ar'
LANGUAGE_CODE = 'es-cl'

#TIME_ZONE = 'America/Argentina/Buenos_Aires'
TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles/'

MEDIA_ROOT = BASE_DIR /'media/'
MEDIA_URL = '/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

"""
Nombre de servidor: smtp.office365.com
Puerto: 587
Método de cifrado: STARTTLS
"""
EMAIL_HOST = "smtp.office365.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'gpslinkrobotic@outlook.com'
EMAIL_HOST_PASSWORD = 'Gp5l1nkR0b0t1c01'

## lista de Email de administradores
EMAIL_REPLY_TO = 'admin@gpslink.com.cl'
EMAIL_SEND_RETRY = 5


if( ALLOWED_HOSTS[1] == '127.0.0.1'):
  HOSTING_URL = f'http://{ALLOWED_HOSTS[1]}:8000'
else:
  HOSTING_URL = f'http://{ALLOWED_HOSTS[1]}'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

'''
  Defines para etiquetas genericas
'''
## longitud maxima para los nombres de la compania
COMPANY_NAME_MAXLEN = 50
## longitud maxima para el numero telefonico
TELEPHONE_NUMBER_MAXLEN = 50
## longitud maxima para el nombre de los productos
PRODUCT_NAME_MAXLEN = 100
## longitud maxima para la descripcion de un producto
PRODUCT_BRIEF_MAXLEN = 500

## longitud maxima de comentario
COMMENT_MAX_LEN = 500

## longitud maxima del error ocurrido al enviar un email automatico.
ERR_MAIL_MAX_LEN = 500


## defines para normalizar los formularios
FORM_TITLE_USERNAME = 'Ingrese el nombre de Usuario'

FORM_TITLE_NAME = 'Ingrese su Nombre'
FORM_TITLE_FIRSTNAME = 'Ingrese Su primer Nombre'
FORM_TITLE_LASTNAME = 'Ingrese Su Apellido'
FORM_TITLE_EMAIL = 'Ingrese Su Dirección de Correo Electronico'
FORM_TITLE_TELEPHONE = 'Ingrese Su Numero de Telefono'
FORM_TITLE_COMMENT = 'Ingrese un comentario de hasta 500 caracteres'
FORM_LENGTH_COMMENT = 500
FORM_TITLE_COMPANYNAME = 'Ingrese el Nombre de la Empresa'
FORM_TITLE_COMPANYTEL1 = 'Ingrese el número de teléfono principal'
FORM_TITLE_COMPANYTEL2 = 'Ingrese un número de teléfono secundario'



FORM_PLACEHOLDER_NAME = 'Nombre *'
FORM_PLACEHOLDER_EMAIL = 'E-mail *'
FORM_PLACEHOLDER_TELEPHONE = 'Teléfono *'
FORM_PLACEHOLDER_COMMENT = 'Mensaje *'




FORM_PLACEHOLDER_USERNAME = 'user name'
FORM_PLACEHOLDER_FIRSTNAME = 'firts name'
FORM_PLACEHOLDER_LASTNAME = 'last name'
#FORM_PLACEHOLDER_TELEPHONE = '+COD XXX-XXX-XXX'
#FORM_PLACEHOLDER_COMMENT = 'comment of to 500 characters'
FORM_PLACEHOLDER_COMPANYNAME = 'Company Name'
FORM_PLACEHOLDER_COMPANYTEL1 = 'main phone number'
FORM_PLACEHOLDER_COMPANYTEL2 = 'secondary phone number'

'''
from config.settings import FORM_TITLE_USERNAME,FORM_TITLE_FIRSTNAME,FORM_TITLE_LASTNAME,FORM_TITLE_EMAIL ,\
  FORM_TITLE_TELEPHONE,FORM_TITLE_COMMENT,FORM_TITLE_COMPANYNAME,FORM_TITLE_COMPANYTEL1,FORM_TITLE_COMPANYTEL2

from config.settings import FORM_PLACEHOLDER_USERNAME, FORM_PLACEHOLDER_FIRSTNAME,FORM_PLACEHOLDER_LASTNAME,\
  FORM_PLACEHOLDER_EMAIL,FORM_PLACEHOLDER_TELEPHONE,FORM_PLACEHOLDER_COMMENT,FORM_PLACEHOLDER_COMPANYNAME,\
  FORM_PLACEHOLDER_COMPANYTEL1,FORM_PLACEHOLDER_COMPANYTEL2
'''
